---
description: "Run Native Huff-language Tests"
inputs:
  with-location:
    default: src
    description: "The location of your huff test files"
    required: false
  with-extension:
    default: .t.huff
    description: "The File extension of your Huff test files"
    required: false
  with-format:
    default: list
    description: "The format of your huff test output"
    required: false

name: "Huff Testing"
runs:
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: "Installing Huff"
      uses: huff-language/huff-toolchain@v2
      with:
        version: nightly

    - if: inputs.with-forge-tests == true
      name: "Installing foundry"
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - run: 'echo "${{ github.action_path }}" >> $GITHUB_PATH'
      shell: bash

    - name: "Running Huff Tests"
      run: "bash hufftests.sh ${{ inputs.with-extension }} ${{ inputs.with-location }} ${{ inputs.with-format }}"
      shell: bash
  using: composite
